# Generated by Django 4.2.4 on 2023-08-23 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcolor_remove_product_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Product type', 'verbose_name_plural': 'Products type'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='CompanyProfile',
            new_name='company_profile',
        ),
    ]
