# Generated by Django 4.2.4 on 2023-08-24 10:45

import apps.products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rebate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rebate',
            options={'verbose_name': 'Rebate', 'verbose_name_plural': 'Rebates'},
        ),
        migrations.AlterField(
            model_name='rebate',
            name='until_time',
            field=models.DateTimeField(validators=[apps.products.validators.validate_rebate_time]),
        ),
    ]
