# Generated by Django 4.2.4 on 2023-08-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_rebate_options_alter_rebate_until_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rebate',
            name='category',
        ),
        migrations.AddField(
            model_name='rebate',
            name='category',
            field=models.ManyToManyField(related_name='rebate_category', to='products.category'),
        ),
    ]
